hackathon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),

    # Regular URLs
    url("^$", views.index, name="index"),
    url("^register/$", views.register, name="register"),
    url("^login/$", views.user_login, name="login"),
    url("^logout/$", views.user_logout, name="logout"),
    url("^update/$", views.update, name="update"),
    url("^hackathon-info/$", views.hackathon_info, name="hackathon_info"),
    url("^competitors/$", views.competitors, name="competitors"),
    url("^teams/$", views.teams, name="teams"),
    url("^notifications/$", views.notifications, name="notifications"),
    url("^contact-support/$", views.contact_support, name="contact_support"),
    url("^success/$", views.success, name="success"),
    url("^create-team/$", views.create_team, name="create_team"),
    url(r'^profile/(?P<user_id>[^/]+)/$', views.view_profile, name='profile'),
    url(r'^view-team/(?P<team_id>[^/]+)/$', views.view_team, name='view_team'),
    url(r'^team/(?P<team_id>[^/]+)/$', views.team, name='team'),
    url(r'^join-team/(?P<team_id>[^/]+)/$', views.join_team, name='join_team'),
    url(r'^leave-team/(?P<team_id>[^/]+)/$', views.leave_team, name='leave_team'),
    url(r'^invite-to-team', views.invite_to_team, name='invite_to_team'),
    url(r'^submit/$', views.submit, name="submit"),
    url(r'^awards/$', views.awards, name="awards"),
    url(r'^team-submissions/$', views.submissions, name="submissions"),
    url(r'^select-team/$', views.select_team, name="select_team"),
    # STAFF VIEWS
    url("^modify-hackathon-info/$", views.modify_hackathon_info, name="modify_hackathon_info"),
    url("^admin-view/$", views.admin_view, name="admin_view"),
    # POST REQUEST
    url(r'^accept-user', views.accept_user, name="accept_user"),
    url(r'^reject-user', views.reject_user, name="reject_user"),
    url(r'^accept-invite', views.accept_invite, name="accept_invite"),
    url(r'^reject-invite', views.reject_invite, name="reject_invite"),
    url(r'^delete-user', views.delete_user, name="delete_user"),
    url(r'^delete-team', views.delete_team, name="delete_team"),
    url(r'^delete-notification', views.delete_notification, name="delete_notification"),
    url(r'^delete-submission', views.delete_submission, name="delete_submission"),
    url(r'^delete-award', views.delete_award, name="delete_award"),
    url(r'^kickout', views.kickout, name="kickout"),
    url(r'^assign-award', views.assign_award, name="assign_award"),

    # Password reset URLs
    url('^', include('django.contrib.auth.urls')),

    # Serving static and media assets
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'hackcollab_app.views.handler404'
handler500 = 'hackcollab_app.views.handler500'

hackcollab_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    url("", include("hackcollab_app.urls")),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'hackcollab_app.views.handler404'
handler500 = 'hackcollab_app.views.handler500'

hackathon/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    id = models.CharField(unique=True, primary_key=True, blank=True, max_length=30)
    team_id = models.CharField(max_length=15, null=True, blank=True)
    birthday = models.DateField()
    title = models.CharField(max_length=100)
    gender = models.CharField(max_length=30)
    phone_number = models.CharField(max_length=30, blank=True)
    # notification_type = models.CharField(max_length=10) # Email, phone, or both

    # Split each area with a tilda "~" into single string
    areas_of_expertise = models.TextField(blank=True)

    # Textarea input - users write a paragraph
    past_accomplishments = models.TextField(blank=True)

    # SOCIAL PROFILES
    github_link = models.CharField(max_length=50, blank=True)
    linkedin_link = models.CharField(max_length=50, blank=True)
    personal_website_link = models.CharField(max_length=50, blank=True)

    profile_picture = models.ImageField(blank=True, null=True)

    # SOFT SKILL RATINGS - rated from 1-10
    communication = models.IntegerField(blank=True)
    public_speaking = models.IntegerField(blank=True)
    teamwork = models.IntegerField(blank=True)
    leadership = models.IntegerField(blank=True)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name


class Team(models.Model):
    id = models.CharField(primary_key=True, unique=True, max_length=15)
    name = models.CharField(max_length=50)
    description = models.TextField()
    leader = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class Notification(models.Model):
    id = models.CharField(primary_key=True, max_length=30)
    title = models.CharField(max_length=50)
    description = models.TextField()
    source_id = models.CharField(max_length=15, null=True, blank=True)
    target_id = models.CharField(max_length=15)
    type = models.CharField(max_length=10) # info or action

    def __str__(self):
        return self.title

class ID(models.Model):
    generated_id = models.CharField(max_length=30)

    def __str__(self):
        return self.generated_id


class Hackathon(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30)
    formal_name = models.CharField(max_length=30)

    def __str__(self):
        return self.formal_name


class HackathonIdentification(models.Model):
    hackathon_name = models.CharField(max_length=30)
    model_id = models.CharField(max_length=30)

    def __str__(self):
        # Getting current hackathon
        hackathon = Hackathon.objects.get(name=self.hackathon_name)

        # Checking what kind of model it is
        id = self.model_id

        # Team
        if id.startswith("t"):
            team = Team.objects.get(id=id)
            return hackathon.formal_name + " - Team " + team.name
        # Notification
        elif id.startswith("n"):
            notification = Notification.objects.get(id=id)
            return hackathon.formal_name + " - Notifcation " + notification.title
        # UserProfile
        else:
            profile = UserProfile.objects.get(id=id)
            return hackathon.formal_name + " - UserProfile " +  profile.user.username


class TeamIdentification(models.Model):
    team_id = models.CharField(max_length=30)
    user_id = models.CharField(max_length=30)

    def __str__(self):
        team = Team.objects.get(id=self.team_id)
        profile = UserProfile.objects.get(id=self.user_id)
        return "Team " + team.name + " - " + profile.user.username


class TeamSubmission(models.Model):
    hackathon_name = models.CharField(max_length=20)
    team_id = models.CharField(max_length=15)
    submission_name = models.CharField(max_length=50)
    submission_description = models.TextField()

    def __str__(self):
        return self.hackathon_name + " - " + self.submission_name


class Award(models.Model):
    id = models.AutoField(primary_key=True)
    hackathon_name = models.CharField(max_length=20)
    title = models.CharField(max_length=30)
    description = models.TextField()
    prize = models.TextField()
    team_id = models.CharField(max_length=15, blank=True, null=True)

    def __str__(self):
        return self.title

hackathon/forms.py
from django import forms
from . import models

class DateInput(forms.DateInput):
    input_type = "date"

class UserForm(forms.ModelForm):
    first_name = forms.CharField(label="First Name *", required=True, widget=forms.TextInput(attrs={"class": "form-control form-input", "placeholder": "First Name"}))
    last_name = forms.CharField(label="Last Name *", required=True, widget=forms.TextInput(attrs={"class": "form-control form-input", "placeholder": "Last Name"}))
    email = forms.CharField(label="Email *", required=True, widget=forms.TextInput(attrs={"class": "form-control form-input", "placeholder": "Email"}))
    username = forms.CharField(label="Username *", required=True, widget=forms.TextInput(attrs={"class": "form-control form-input", "placeholder": "Username"}))
    password = forms.CharField(label="Password *", required=True, widget=forms.PasswordInput(attrs={"class": "form-control form-input", "placeholder": "Password"}))
    birthday = forms.DateField(label="Birthday *", required=True)
    title = forms.CharField(label="Title *", required=True, widget=forms.TextInput(attrs={"class": "form-control form-input", "placeholder": "Title"}))

    gender_choices = (
        ('Male', "Male"),
        ('Female', 'Female'),
        ("Binary", "Binary")
    )
    gender = forms.ChoiceField(choices=gender_choices)

    phone_number = forms.CharField(required=False, widget=forms.TextInput(attrs={"class": "form-control form-input", "placeholder": "Phone Number"}))

    # notification_type_choices = (
    #     ('email', "Email"),
    #     ('phone', 'Phone'),
    #     ("both", "Both")
    # )
    # notification_type = forms.ChoiceField(choices=notification_type_choices)

    areas_of_expertise = forms.CharField(required=False, widget=forms.Textarea(attrs={"class": "form-control form-input", "placeholder": "Write about your areas of expertise"}))
    past_accomplishments = forms.CharField(required=False, widget=forms.Textarea(attrs={"class": "form-control form-input", "placeholder": "Write about your past accomplishments"}))
    github_link = forms.CharField(required=False, widget=forms.URLInput(attrs={"class": "form-control form-input", "placeholder": "Link to GitHub"}))
    linkedin_link = forms.CharField(required=False, widget=forms.URLInput(attrs={"class": "form-control form-input", "placeholder": "Link to LinkedIn"}))
    personal_website_link = forms.CharField(required=False, widget=forms.URLInput(attrs={"class": "form-control form-input", "placeholder": "Link to Personal Website"}))
    profile_picture = forms.ImageField(label="Choose a File", required=False, widget=forms.FileInput(attrs={"class": "inputfile", "id": "file", "name": "file", "data-multiple-caption": "{count} files selected"}))

    # communication = forms.IntegerField()
    # public_speaking = forms.IntegerField()
    # teamwork = forms.IntegerField()
    # leadership = forms.IntegerField()

    class Meta:
        model = models.UserProfile
        fields = ('first_name', 'last_name', 'email', 'username', 'password', 'birthday', 'title', 'gender', 'phone_number', 'areas_of_expertise', 'past_accomplishments', 'github_link', 'linkedin_link', 'personal_website_link', 'profile_picture',)

templates/hackathon/admin_view.html
{% load staticfiles %}
{% include 'hackathon/base.html' %}
<link rel="stylesheet" href="{% static 'hackathon/teams.css' %}">
<link rel="stylesheet" href="{% static 'hackathon/competitors.css' %}">
<link rel="stylesheet" href="{% static 'hackathon/awards.css' %}">
<link rel="stylesheet" href="{% static 'hackathon/admin_view.css' %}">
<title>HackCollab - Administrator View</title>
{% block body %}
  <style>
    /* Removing darken hover effect */
    .team:hover {
      background-color: white;
    }
  </style>
  <div class="p-5">
    <h1 class="header">Administrator View</h1>
    <h1 class="subheader">Competitors</h1>
    <div class="container">
      {% if competitors %}
        <div class="competitors">
          {% for competitor in competitors %}
            <div class="competitor">
              <div class="image-cropper">
                <img class="profile-picture" src="/media/{{competitor.profile_picture}}" alt="">
              </div>
              <a href="/profile/{{competitor.id}}"><h4>{{competitor.user.username}}</h4></a>
              <p style="margin-bottom: 0 !important;">{{competitor.title}}</p>
              <a href="/delete-user?id={{competitor.id}}" class="btn btn-outline-primary mt-3">Delete User</a>
            </div>
          {% endfor %}
        </div>
      {% else %}
        <small style="color: white;">No competitors yet!</small>
      {% endif %}
    </div>
    <h1 class="subheader">Teams</h1>
    <div class="container">
      {% if teams %}
        <div class="teams">
          {% for team, teammates in teams.items %}
            <div class="team">
              <h2>{{team.name}}</h2>
              <p>
                <strong>Description:</strong> {{team.description}}
              </p>
              <strong>Team Members:</strong>
              <ul class="team-members-list fa-ul">
                {% for teammate in teammates %}
                  <li>
                    <span class="fa-li"><i class="fas fa-angle-right"></i></span>
                    <a style="color: black;" href="/profile/{{teammate.id}}">{{teammate.user.username}}</a>
                  </li>
                {% endfor %}
              </ul>
              <a href="/delete-team?id={{team.id}}" class="btn btn-outline-primary">Delete Team</a>
            </div>
          {% endfor %}
        </div>
      {% else %}
        <small>No teams yet!</small>
      {% endif %}
    </div>
    <h1 class="subheader">Team Submissions</h1>
    <div class="container">
      {% if submissions %}
        <ul class="list-group">
          <p class="submission-item" style="color: white;">
            <span>Counter</span>
            <span>Team</span>
            <span>Submission Name</span>
            <span>Submission Description</span>
            <span>Delete</span>
          </p>
          {% for number, team, submission in submissions %}
            <li class="list-group-item submission-item">
              <span>{{number}}.</span>
              <a href="/team/{{team.id}}">{{team.name}}</a>
              <span>{{submission.submission_name}}</span>
              <span>{{submission.submission_description}}</span>
              <a href="/delete-submission?id={{team.id}}" class="btn btn-danger btn-inline">Delete</a>
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <small style="color: white;">No submissions yet!</small>
      {% endif %}
    </div>
    <h1 class="subheader" style="position: relative;">
      Awards
      <button style="position: absolute !important; right: 0;" class="btn btn-outline-light" data-toggle="modal" data-target="#addAward">Add Award</button>
    </h1>
    <div class="container">
      <div class="awards-grid">
        {% if awards %}
          {% for award, team in awards.items %}
            <div class="award">
              <h3>{{award.title}}</h3>
              <p>
                <strong>Description:</strong> {{award.description}}
              </p>
              <p>
                <strong>Prize:</strong> {{award.prize}}
              </p>
              {% if not team %}
                <small><strong>Winner not announced yet!</strong></small>
              {% else %}
                <strong>Winner:</strong> <a href="/view-team/{{team.id}}">{{team.name}}</a> <a href="/assign-award?award_id={{award.id}}&team_id=None" class="btn btn-danger btn-sm">Remove</a>
              {% endif %}
              <div class="mt-3">
                <a href="/select-team?award_id={{award.id}}" class="btn btn-success">Select Winner</a>
                <a href="#" data-toggle="modal" data-target="#exampleModal" class="btn btn-secondary">Update</a>
                <a href="/delete-award?id={{award.id}}" class="btn btn-danger">Delete</a>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <small style="color: white;">No awards yet!</small>
        {% endif %}
      </div>
    </div>
  </div>

  <!-- MODALS -->
  {% for award, team in awards.items %}
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Update Award</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form id="updateForm{{award.id}}" method="post">
              {% csrf_token %}
              <input type="hidden" name="type" value="update">
              <input type="hidden" name="id" value="{{award.id}}">
              <input class="form-control" type="text" name="title" placeholder="Title" value="{{award.title}}">
              <textarea class="my-3 form-control" name="description" rows="6" placeholder="Description">{{award.description}}</textarea>
              <input type="text" name="prize" placeholder="Prize" class="form-control" value="{{award.prize}}">
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" onclick="submitForm('#updateForm{{award.id}}')">Update Award</button>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}

  <div class="modal fade" id="addAward" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Add Award</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form id="addForm" method="post">
            {% csrf_token %}
            <input type="hidden" name="type" value="add">
            <input class="form-control" type="text" name="title" placeholder="Title">
            <textarea class="my-3 form-control" name="description" rows="6" placeholder="Description"></textarea>
            <input type="text" name="prize" placeholder="Prize" class="form-control">
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" onclick="submitForm('#addForm')">Add Award</button>
        </div>
      </div>
    </div>
  </div>

  <script>
    function submitForm(form_id) {
      document.querySelector(form_id).submit()
    }
  </script>
{% endblock %}

templates/hackathon/awards.html
{% load staticfiles %}
{% include 'hackathon/base.html' %}
<title>HackCollab - Awards</title>
<link rel="stylesheet" href="{% static 'hackathon/awards.css' %}">
{% block body %}
  <h1 class="header">Awards</h1>
  <div class="container">
    {% if awards %}
      <div class="awards-grid">
        {% for award, team in awards.items %}
          <div class="award">
            <h3>{{award.title}}</h3>
            <p>
              <strong>Description:</strong> {{award.description}}
            </p>
            <p>
              <strong>Prize:</strong> {{award.prize}}
            </p>
            {% if not team %}
              <small><strong>Winner not announced yet!</strong></small>
            {% else %}
              <strong>Winner:</strong> <a href="/view-team/{{team.id}}">{{team.name}}</a>
            {% endif %}
          </div>
        {% endfor %}
      </div>
    {% else %}
      <div class="text-center">
        <small style="color: white;">No awards yet!</small>
      </div>
    {% endif %}
  </div>
{% endblock %}

templates/hackathon/competitors.html
{% load staticfiles %}
{% include 'hackathon/base.html' %}
<title>HackCollab - Competitors</title>
<link rel="stylesheet" href="{% static 'hackathon/competitors.css' %}">
{% block body %}
    <h1 class="header">Competitors</h1>
    <div class="container">
      {% if competitors %}
        <div class="competitors">
          {% for competitor, parameters in competitors.items %}
            <div class="competitor">
              <div class="image-cropper">
                <img class="profile-picture" src="/media/{{competitor.profile_picture}}" alt="">
              </div>
              <a href="/profile/{{competitor.id}}"><h4>{{competitor.user.username}}</h4></a>
              <p style="margin-bottom: 0 !important;"><strong>Title:</strong> {{competitor.title}}</p>
              {% if parameters.team %}
                <div>
                  <strong>Team:</strong> <a href="/view-team/{{parameters.team.id}}">{{parameters.team.name}}</a>
                </div>
              {% endif %}
              {% if request.user.profile.team_id %}
                {% if parameters.invite %}
                  {% if parameters.max %}
                    <small>Max amount of team members reached!</small>
                  {% else %}
                    <a class="btn btn-primary" href="/invite-to-team?team_id={{request.user.profile.team_id}}&user_id={{competitor.id}}">Invite to team</a>
                  {% endif %}
                {% else %}
                  <small>{{competitor.user.username}} is already on your team</small>
                {% endif %}
              {% endif %}
            </div>
          {% endfor %}
        </div>
      {% else %}
        <div class="text-center">
          <small style="color: white;">No competitors yet!</small>
        </div>
      {% endif %}
    </div>
{% endblock %}

templates/hackathon/contact_support.html
{% load staticfiles %}
{% include 'hackathon/base.html' %}
<link rel="stylesheet" href="{% static 'hackathon/contact_support.css' %}">
<title>HackCollab - Contact Support</title>
{% block body %}
  <div class="content">
    <h1 class="header">Contact Us</h1>
    <p class="contact-us-description text-center">
      We guarantee a response within 12 hours!
    </p>
    <form class="contact-us-form" enctype="multipart/form-data" method="post">
      {% csrf_token %}
      <label for="#name">Name:</label>
      <input class="form-input" id="name" type="text" name="name" placeholder="Name">

      <label for="#email">Email Address:</label>
      <input class="form-input" id="email" type="email" name="email" placeholder="Email">

      <label for="#message">Message:</label>
      <textarea class="form-input" id="message" name="message" rows="6" placeholder="Message"></textarea>

      <input class="ghost-cta-button" type="submit" value="Contact Us">
    </form>
  </div>
{% endblock %}

templates/hackathon/create_team.html
{% include 'hackathon/base.html' %}
<title>HackCollab - Create Team</title>
{% block body %}
    <div class="container">
      <div class="float-container">
        <h1>Create Team</h1>
        <form class="form-group" method="post">
          {% csrf_token %}
          <input class="form-control my-5" type="text" name="name" placeholder="Team Name">
          <textarea class="form-control my-5" name="description" rows="6" cols="50" placeholder="Team Description"></textarea>
          <input class="btn btn-outline-primary btn-block my-5" type="submit" value="Create Team">
        </form>
      </div>
    </div>
{% endblock %}

templates/hackathon/hackathon_info.html
{% load staticfiles %}
{% include 'hackathon/base.html' %}
<link rel="stylesheet" href="{% static 'hackathon/hackathon_info.css' %}">
<title>HackCollab - {{hackathon.formal_name}}</title>
{% block body %}
  <h1 class="header">{{hackathon.formal_name}} Information</h1>
  <div class="info w-50 m-auto">
    {{html}}
  </div>
  {% if request.user.is_staff %}
    <div class="text-center my-5">
      <a class="btn btn-outline-light btn-lg" href="/modify-hackathon-info/">Modify</a>
    </div>
  {% endif %}
{% endblock %}

templates/hackathon/join_team.html
{% include 'hackathon/base.html' %}
<title>HackCollab - Join Team</title>
{% block body %}
  <div class="float-container" style="width: 50%;">
    <h1>Join Team Request</h1>
    <p>
      Write a request about why you want to join this team and why you would be a good person to work with
    </p>
    <form class="form-group" method="post">
      {% csrf_token %}
      <input class="form-control my-4" type="text" name="title" value="Join Team Request" placeholder="Title">
      <textarea class="form-control my-4" name="description" rows="8" cols="80" placeholder="Description"></textarea>
      <input class="btn btn-outline-primary btn-block my-4" type="submit" value="Send Request">
    </form>
  </div>
{% endblock %}

templates/hackathon/modify_hackathon_info.html
{% load staticfiles %}
{% include 'hackathon/base.html' %}
<link rel="stylesheet" href="{% static 'hackathon/modify_hackathon_info.css' %}">
<title>HackCollab - Modify Hackathon Information</title>
{% block body %}
  <h1 class="header">Modify Hackathon Information</h1>
  <form class="hackathon-info-form w-50 m-auto" method="post">
    {% csrf_token %}
    <textarea class="hackathon-info-input form-control" name="hackathon_info" rows="20">{{markdown}}</textarea>
    <div class="text-center my-3">
      <input class="btn btn-outline-light btn-lg" type="submit" value="Update Info">
    </div>
  </form>
{% endblock %}

templates/hackathon/notifications.html
{% load staticfiles %}
{% include 'hackathon/base.html' %}
<title>HackCollab - Notifications</title>
<link rel="stylesheet" href="{% static 'hackathon/notifications.css' %}">
{% block body %}
  <div class="container mt-5">
    <div class="float-container">
      <h1>Notifications</h1>
      {% if notifications %}
        <ul class="list-group">
          {% for notification, team in notifications.items %}
            <div class="notification list-group-item">
              <h3>{{notification.title}}</h3>
              <p>
                {{notification.description}}
              </p>
              {% if team %}
                <p>
                  <strong>From:</strong> <a href="/team/{{team.id}}">{{team.name}}</a>
                </p>
              {% endif %}
              {% if notification.type == "action" %}
                <div class="btn-group">
                  <a class="btn btn-primary" href="/accept-invite?team_id={{notification.source_id}}&user_id={{request.user.profile.id}}&notification_id={{notification.id}}">Accept</a>
                  <a class="btn btn-primary" href="/reject-invite?team_id={{notification.source_id}}&user_id={{request.user.profile.id}}&notification_id={{notification.id}}">Reject</a>
                </div>
              {% else %}
                <button class="x" type="button" onclick="deleteNotification('{{notification.id}}')">&times;</button>
              {% endif %}
            </div>
          {% endfor %}
        </ul>
      {% else %}
        <small class="d-block text-center">No notifications!</small>
      {% endif %}
    </div>
  </div>

  <script>
    async function deleteNotification(id) {
      let response = fetch("/delete-notification?id=" + id)
      location.reload()
    }
  </script>
{% endblock %}

templates/hackathon/update.html
{% load staticfiles %}
{% include 'hackathon/base.html' %}
<title>HackCollab - Update Profile</title>
<link rel="stylesheet" href="{% static 'hackathon/register.css' %}">
<link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
{% block body %}
  <div class="container">
    <div class="form-container">
      <h1>Update Profile</h1>
      <form class="" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <h3>Rate your soft skills</h3>
        <label for=".communication-container">Communication:</label>
        <div class="communication-container">
          <label for="#communication" id="communicationInput">{{communication}}</label>
          <input id="communication" type="range" name="communication" min="0" max="10" value="{{communication}}" onchange="updateTextInput(this.value, 'communicationInput');">
        </div>

        <label for=".public-speaking-container">Public Speaking:</label>
        <div class="public-speaking-container">
          <label for="#public-speaking" id="public-speakingInput">{{public_speaking}}</label>
          <input id="public-speaking" type="range" name="public-speaking" min="0" max="10" value="{{public_speaking}}" onchange="updateTextInput(this.value, 'public-speakingInput');">
        </div>

        <label for=".teamwork-container">Teamwork:</label>
        <div class="teamwork-container">
          <label for="#teamwork" id="teamworkInput">{{teamwork}}</label>
          <input id="teamwork" type="range" name="teamwork" min="0" max="10" value="{{teamwork}}" onchange="updateTextInput(this.value, 'teamworkInput');">
        </div>

        <label for=".leadership-container">Leadership:</label>
        <div class="leadership-container">
          <label for="#leadership" id="leadershipInput">{{leadership}}</label>
          <input id="leadership" type="range" name="leadership" min="0" max="10" value="{{leadership}}" onchange="updateTextInput(this.value, 'leadershipInput');">
        </div>
        <input class="btn btn-outline-primary btn-block" type="submit" value="Update Profile">
      </form>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
    function updateTextInput(val, id) {
      document.getElementById(id).innerHTML=val;
    }

    $( function() {
      $( "#id_birthday" ).datepicker();
    } );

    document.querySelector("#id_password").removeAttribute("required")
    document.querySelector("#id_password").parentElement.style.display = "none"
  </script>
{% endblock %}